name: DELETER 1-20
on:
  schedule:
    - cron: 1 * */30 * *
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.baru1 }}
        EOF
    - name: DELETE 1
      run: |
         rclone delete "S1:" --drive-use-trash=false
    - name: DELETE 2
      run: |
         rclone delete "S2:" --drive-use-trash=false
#    - name: DELETE 3
#      run: |
#         rclone delete "S3:" --drive-use-trash=false
    - name: DELETE 4
      run: |
         rclone delete "S4:" --drive-use-trash=false
    - name: DELETE 5
      run: |
         rclone delete "S5:" --drive-use-trash=false
    - name: DELETE 6
      run: |
         rclone delete "S6:" --drive-use-trash=false
    - name: DELETE 7
      run: |
         rclone delete "S7:" --drive-use-trash=false
    - name: DELETE 8
      run: |
         rclone delete "S8:" --drive-use-trash=false
    - name: DELETE 9
      run: |
         rclone delete "S9:" --drive-use-trash=false
    - name: DELETE 10
      run: |
         rclone delete "S10:" --drive-use-trash=false
    - name: DELETE 11
      run: |
         rclone delete "S11:" --drive-use-trash=false
    - name: DELETE 12
      run: |
         rclone delete "S12:" --drive-use-trash=false
    - name: DELETE 13
      run: |
         rclone delete "S13:" --drive-use-trash=false
    - name: DELETE 14
      run: |
         rclone delete "S15:" --drive-use-trash=false
    - name: DELETE 15
      run: |
         rclone delete "S15:" --drive-use-trash=false
    - name: DELETE 16
      run: |
         rclone delete "S16:" --drive-use-trash=false
    - name: DELETE 17
      run: |
         rclone delete "S17:" --drive-use-trash=false
    - name: DELETE 18
      run: |
         rclone delete "S18:" --drive-use-trash=false
    - name: DELETE 19
      run: |
         rclone delete "S19:" --drive-use-trash=false
    - name: DELETE 20
      run: |
         rclone delete "S20:" --drive-use-trash=false
