name: kirim-kirim 2
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  UpdateSub:
    runs-on: ubuntu-latest

    steps:
      - name: Check The Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-telegram-bot==13.15 requests
      - name: Get Files
        run: |
          curl -o aktif1.txt -LJO https://random.situs.workers.dev/?gist=https://5412.us.to/api/v1/sub?vpn=vless,trojan
          curl -o vmess.txt -LJO https://random.situs.workers.dev/?gist=https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/VM_TrinityBase
          curl -o vmess1.txt https://random.situs.workers.dev/?gist=https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/vmess_configs.txt

      - name: send to telegram
        run: |
          python3 kirim.py ${{ secrets.BOT }} -1002292042831 aktif1.txt && python3 test.py ${{ secrets.BOT }} -1002292042831 vmess.txt && python3 test.py ${{ secrets.BOT }} -1002292042831 vmess1.txt 

